default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: timetracker_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: timetracker_test
  username: postgres
  password: postgres
  host: localhost


production:
  <<: *default
  database: timetracker_production
  username: postgres
  password: <%= ENV['TIMETRACKER_DATABASE_PASSWORD'] %>